on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn clean install -Drat.skip=true --no-transfer-progress

    - name: Deploy with Maven
      run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} -Drat.skip=true --no-transfer-progress -X
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
